# Generated by Django 5.1.2 on 2025-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mealplan_trainingplan_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercices',
            field=models.CharField(default='Abgeschlossene Übungen', max_length=100),
            preserve_default=False,
        ),
    ]
