# Generated by Django 5.1.2 on 2025-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_workout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplan',
            old_name='goal',
            new_name='category',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise1',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise2',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise3',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise4',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise5',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='exercise6',
            field=models.CharField(default='Übung', max_length=100),
            preserve_default=False,
        ),
    ]
