# Generated by Django 5.1.2 on 2025-01-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0006_remove_workout_exercices_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='breakfast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner',
            field=models.CharField(default='Abendessen', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch',
            field=models.CharField(default='Mittagessen', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
