# Generated by Django 5.1.2 on 2025-01-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0008_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='exercise3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='exercise4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='exercise5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='exercise6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
