# Generated by Django 5.1.2 on 2025-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0009_alter_trainingplan_exercise3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.TextField(default='Kategorie', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(max_length=100),
        ),
    ]
