# Generated by Django 5.1.2 on 2025-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0011_alter_coach_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
